version: "3.8"
name: "quizlet-api"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: quizlet-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: kelvin
      RABBITMQ_DEFAULT_PASS: kelvin
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq