version: "3.8"
name: "quizlet"
services:
  db:
    container_name: quizlet-postgresql
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=quizlet
      - POSTGRES_PASSWORD=quizlet
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - quizlet-network
  keycloak:
    container_name: quizlet-keycloak
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_HTTP_PORT=8081
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=quizlet
      - KEYCLOAK_DATABASE_SCHEMA=keycloak
      - KEYCLOAK_DATABASE_USER=quizlet
      - KEYCLOAK_DATABASE_PASSWORD=quizlet
    depends_on:
      - db
    networks:
      - quizlet-network
  redis:
    image: redis:6.2-alpine
    container_name: quizlet-redis
    ports:
      - "6379:6379"
    # User default
    command: redis-server --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./volumes/cache:/data
    networks:
      - quizlet-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: quizlet-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: quizlet
      RABBITMQ_DEFAULT_PASS: quizlet
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - quizlet-network

networks:
  quizlet-network: {}