name: Build And Push Images to Dockerhub

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: "quizlet-api"

jobs:
  build_docker_images:
    name: Build Docker Image To Dockerhub
    runs-on: [ubuntu-latest]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}
          tags: type=sha,format=long

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          logout: true

      - name: Build And Push
        uses: docker/build-push-action@v5
        with:
          context: . # indicates the location of the Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
